### ISSUE TITLE
Bad Style

### ISSUE THREAD

**Issue by wafer-li** [poooi/plugin-hensei-nikki#14]
![qq 20151009233159](https://cloud.githubusercontent.com/assets/12459199/10396641/962388e8-6ede-11e5-91a0-8bd0ab56bb50.png)

**Comment by Astra-RX** [comment]
A fix for testing.
https://github.com/poooi/plugin-hensei-nikki/tree/fix_to_issue_14

**Comment by wafer-li** [comment]
Already Fixed.
