### ISSUE TITLE
Delete the poi.alert.error on failing reading hensei data

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/plugin-hensei-nikki#18]
index.cjsx line 223
在不存在编成文件的时候会在poi.alert.error处打印一条出错信息
然而第一这并不需要提醒，第二这发生在api_start2之后几乎会被被别的收发包log瞬间淹没，第三这影响到了DYK插件的初始那一条tip……
（我猜本来是想要console.error？然而我觉得这也够不上error，甚至连warning也够不上吧，因为没有文件是正常的……）

**Comment by Ayaphis** [comment]
(感觉是写try catch的习惯

**Comment by dkwingsmt** [comment]
然而使用了错误的error函数⋯⋯
