### ISSUE TITLE
希望显示具体装备信息

### ISSUE THREAD

**Issue by Chibaheit** [poooi/plugin-hensei-nikki#2]
目前hover的方式不太适合回去翻 而且间距有些大可以缩小一点两个索敌建议加个括号说明?

**Comment by ruiii** [comment]
的确，但是考虑到双栏模式位置不够，所以得想想怎么布局。
除了kcv那种竖排装备名带图标的之外 还有什么别的布局建议吗？

**Comment by hanzhao** [comment]
看来又要变成一个新窗口100M了

**Comment by taroxd** [comment]
其实我还想生成 [艦隊シミュレーター＆デッキビルダー](http://www.kancolle-calc.net/deckbuilder.html) 的代码，可以看到更多详细数据的样子 >_<

不过好像不支持第五格装备栏

**Comment by ruiii** [comment]
显示装备具体信息 √
支持 艦載機厨デッキビルダー&WhoCallsTheFleet 代码导入导出 √
