### ISSUE TITLE
“添加”一栏改为“当前舰队”

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/plugin-hensei-nikki#23]
编成日记最常见的用法之一是用来把当前舰队（四个之一）截图或者发给别人看。
建议把“添加”一栏改为“当前舰队”，这样可以大大方便和激励人们使用该插件。

设计用法如下：

一个下拉菜单（只能四选一）
下面直接渲染当前舰队的编成排版
一个按钮（或者一个文本框）用来复制当前舰队代码（不用保存）

还可以加一个按钮可以弹出，在一个单独的对话框中完整显示当前舰队大图，以免有小屏者用着小窗口。

**Comment by ruiii** [comment]
不保存？那日记就不是日记了呀。。

**Comment by yukixz** [comment]
hmm... 我同意 DK 的想法。
并不是不保存、而是添加界面就直接显示出舰队配置。
可以避免想要看舰队配置的时候，需要保存再切换过去看的麻烦。

**Comment by Ayaphis** [comment]
直观的显示所选的舰队（希望保存的）配置？
感觉需要能重复使用的舰队显示方案
某种意义上，不如往舰队面板塞记录日记的按钮（x

**Comment by yukixz** [comment]
舰队面板不能显示装备名字= =
舰队显示抽象成一个模块出来，然后用 `@props` 传舰队配置就好=。=

**Comment by yukixz** [comment]
舰队面板不能显示装备名字= =
舰队显示抽象成一个模块出来，然后用 @props 传舰队配置就好=。=

**Comment by yukixz** [comment]
舰队面板不能显示装备名字= =
舰队显示抽象成一个模块出来，然后用 @props 传舰队配置就好=。=

**Comment by dkwingsmt** [comment]
而且你无法使用插件往舰队面板添加按钮

**Comment by ruiii** [comment]
添加改成当前舰队。。？是什么意思我不太清楚 改名吗

**Comment by dkwingsmt** [comment]
![image](https://cloud.githubusercontent.com/assets/1596656/11107237/6ce29c9e-88a1-11e5-8175-208324e98a14.png)
大概的想法是长这样
（我随意编辑了一下html的概念图，暂时不要考虑高度的问题……）

**Comment by ruiii** [comment]
恩 明白这个预览 
只是tag名字改成“当前舰队” 不太明白

**Comment by dkwingsmt** [comment]
这一个页面不就是用来处理“当前（四个）舰队”的么……我觉得这样稍微清楚一点。毕竟，
“添加”可以指 从代码添加一个新纪录

**Comment by dkwingsmt** [comment]
顺便这么说的话……我觉得第二个选项卡改名叫“代码”？……

**Comment by ruiii** [comment]
不行不行 “代码”的话 用户更不知道了。。

**Comment by dkwingsmt** [comment]
主要是我每次看到这个都会想半天
这个添加，到底是从代码添加，还是从舰队添加？
这个导入，到底是从代码导入，还是从舰队导入？

**Comment by ruiii** [comment]
做个预览按钮吗。。比较好控制render

**Comment by dkwingsmt** [comment]
好像也不错
