### ISSUE TITLE
[Enhancement Request] 在配装记录界面中显示所添加的 Tag

### ISSUE THREAD

**Issue by wafer-li** [poooi/plugin-hensei-nikki#27]
![qq 20151212012848](https://cloud.githubusercontent.com/assets/12459199/11749200/b709fbc4-a06f-11e5-8b0b-212b4194b27d.png)

嗯，就是在这个界面中显示所添加的 Tag。
个人的想法是显示在制空索敌的旁边，这样显示出来的信息就更加清晰。

舰队的配装总是需要进行调整的，但是地图的硬性要求确是不变的，这样子的话，对于进行一些配装的微调很有帮助。

**Comment by ruiii** [comment]
双栏的话布局会爆炸（
最初的版本还有个comment，就是放在索敌的旁边
因为布局问题删掉了

**Comment by wafer-li** [comment]
:joy:  呃……看来我只是从纵版布局进行思考了，横版布局下的空间的确比较紧张。

**Comment by wafer-li** [comment]
:joy:  不过我倒发现了一个其他的问题，纵横版布局切换之后名字就变成英文了，修改语言设置，重启程序也没什么卵用。
![qq 20151212154246](https://cloud.githubusercontent.com/assets/12459199/11760679/028090b4-a0e7-11e5-887f-ed15f7b2c28c.png)

**Comment by ruiii** [comment]
这部分i18n我修改了，更新试试？

**Comment by wafer-li** [comment]
:flushed: 恩，i18n 修复了。

**Comment by wafer-li** [comment]
几个新版本之后尝试了一下，发现本质问题在于 TAG 的显示不够醒目，但是现在这个版本（至少我）在使用过程中觉得已经足够醒目了。嗯。
