### ISSUE TITLE
无法导入记录文件

### ISSUE THREAD

**Issue by wafer-li** [poooi/plugin-hensei-nikki#33]
点击导入文件之后不显示。

如图
![qq 20160401221956](https://cloud.githubusercontent.com/assets/12459199/14207965/f4bdd9fa-f857-11e5-83a0-427e37985f7d.png)

**Comment by ruiii** [comment]
求截图看下具体是哪行的报错

**Comment by wafer-li** [comment]
@ruiii 

![qq 20160401223426](https://cloud.githubusercontent.com/assets/12459199/14208378/00f5085e-f85a-11e5-9806-8d6b486e37c5.png)

![qq 20160401223544](https://cloud.githubusercontent.com/assets/12459199/14208396/1ad1aa2a-f85a-11e5-8412-77ea672be919.png)

**Comment by ruiii** [comment]
QwQ 导入的文件有问题？ 可以发我一份吗

**Comment by wafer-li** [comment]
@ruiii 

没在你的 profile 找到邮箱。

顺便一提，这个文件我在 mac 上导入是没有问题的。

**Comment by ruiii** [comment]
啊？报错的时候用的什么系统？

**Comment by wafer-li** [comment]
@ruiii 

:joy: 
win 10 pro x64

两个系统都是
electron v0.36.12

插件版本 3.6.0

**Comment by ruiii** [comment]
mac 上没问题的话 win 上应该也没问题才是。。
以前在 win 上有导入过吗？

**Comment by wafer-li** [comment]
@ruiii 

API 1.0 的时候试过，现在改了 API 之后是第一次试。

**Comment by ruiii** [comment]
这样啊
那麻烦更新下 poi 版本
然后更新插件 再试试？

**Comment by wafer-li** [comment]
resolved.

估计是之前本体更新引起的问题。
