### ISSUE TITLE
制空公式需要更新

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/plugin-hensei-nikki#34]
制空公式需要根据本体进行更新~

![image](https://cloud.githubusercontent.com/assets/1596656/16547255/9cb06f70-412c-11e6-9a31-bbe75a986707.png)
![image](https://cloud.githubusercontent.com/assets/1596656/16547256/a0f5887c-412c-11e6-8c14-3510d8d441fa.png)

**Comment by ruiii** [comment]
猴
上面两个东西都是显示 xxx ~ xxx 我们要不要也这样（x

**Comment by dkwingsmt** [comment]
我不知道呀，建议你问个吃吧？

**Comment by dkwingsmt** [comment]
噢这个好像是因为熟练度有小数点吧。我觉得可以不用

**Comment by taroxd** [comment]
我记得本体是在 Tooltip 里显示 xxx~xxx 的吧

**Comment by KochiyaOcean** [comment]
本体现在默认显示最大值，然后 tooltip 里有显示可能的范围

**Comment by dkwingsmt** [comment]
其实我觉得应该默认显示最小值……

**Comment by KochiyaOcean** [comment]
不知道吃吧怎么想的，可以去干死他

**Comment by ruiii** [comment]
@Chibaheit
