### ISSUE TITLE
中文输入法问题？

### ISSUE THREAD

**Issue by wafer-li** [poooi/plugin-hensei-nikki#37]
OSX 10.11.6
搜狗
poooi/poi@cb60331

编辑 Tag 时只能一个字一个字打，打多了就出不来字。

**Comment by ruiii** [comment]
这边 arch 没问题。。晚上回去用 mac 试试

**Comment by wafer-li** [comment]
只在 **编辑** 界面有问题

**新建** 界面没问题

**Comment by ruiii** [comment]
在 mac 上按下 cmd 键就会出现失去焦点的问题 与本体设置里地址栏的表现一致 应该是本体的问题
