### ISSUE TITLE
关于索敌的显示问题

### ISSUE THREAD

**Issue by wafer-li** [poooi/plugin-hensei-nikki#7]
个人认为，索敌应该优先显示2-5秋式的索敌值，理由有2
1. 2-5秋是新公式，可靠性较高。
2. 在通常海域作战，有且仅有2-5会遇到索敌不足的问题，而2-5旧式已经被证明在此处不适用，而应使用2-5秋式作为新的索敌计算方法。

**Comment by yukixz** [comment]
默认是秋式啊= =

**Comment by wafer-li** [comment]
![qq 20150915115411](https://cloud.githubusercontent.com/assets/12459199/9866716/d6b5e3fc-5ba0-11e5-96c8-ae02aebc937d.png)

本人使用的目前版本为
commit SHA: 35f6b5fb321431d66007ce0b6c9b1c9281fabc91
不知道是否已经落后。

**Comment by yukixz** [comment]
哦...
没注意这是 hensennikki... 还以为是 poi 本体... 
抱歉=。=

**Comment by ruiii** [comment]
喔。。这个我也发现了 之前懒得修（。

**Comment by wafer-li** [comment]
checked
