### ISSUE TITLE
关于导出全部数据的问题

### ISSUE THREAD

**Issue by wafer-li** [poooi/plugin-hensei-nikki#8]
希望提供一个导出全部记录的功能，最好是能导出一个文件。

本人是学生党，免不了要使用PC和平板进行肝船，所以对数据的同步有一个比较高的需求。
特别是这种专门储存一些出击用配置的插件，对数据的跨平台同步有着比其他插件和本体更高的要求。
鉴于目前建立一个有效的跨平台同步系统存在诸多障碍，所以不如将所有数据导出，然后玩家可以采取百度云之类的应用进行同步。

或许应该有一个更好的办法？

**Comment by ruiii** [comment]
这样导出的整个文件只支持编成日记

**Comment by wafer-li** [comment]
checked
